services:
  api:
    build: ./api
    container_name: mortgage-simulator
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    container_name: db-mortgage
    image: postgres:16
    env_file:
      - ./api/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
